export CUDA_VISIBLE_DEVICES=0
python3 run.py \
    --task_name ERTESD2 \
    --max_seq_length 150 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 16 \
    --learning_rate 5e-5 \
    --num_train_epochs 100 \
    --logging_dir ./tb_logs \
    --logging_steps 50 \
    --eval_steps 1000 \
    --save_steps 5000 \
    --evaluation_strategy steps \
    --warmup_ratio 0.1 \
    --model_dir ./bert-base-chinese/ \
    --output_dir ./output/ccl \
    --overwrite_output_dir \
    --dataset_dir data \
    --dataloader_pin_memory \
    --dataloader_num_workers 4 \
    --lr_scheduler_type cosine \
    --seed 2023 \
    --do_test_all_checkpoints\
    --dataset_name ccl \
    --test_data_type ERTESD_span \
    --threshold 0.5 \
    --do_train